apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    {{- include "app.defaultAnnotations" . | indent 4 }}
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ include "app.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    {{- include "app.matchLabels" . | indent 4 }}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ include "app.fullname" . }}
      from:
        kind: ImageStreamTag
        name: "{{ include "app.fullname" . }}:{{ .Chart.AppVersion }}"
    type: ImageChange
  strategy:
    type: Rolling
  template:
    metadata:
      annotations:
        {{- include "app.defaultAnnotations" . | indent 8 }}
      labels:
        {{- include "app.defaultLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - image: "{{ include "app.fullname" . }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: {{ include "app.fullname" . }}
          volumeMounts:
            - mountPath: /etc/certs
              name: volume-certs
              readOnly: true
          ports:
            - name: main
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-config
          resources: {}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if .Values.deployment.includeHealthChecks }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
      volumes:
        - name: volume-certs
          secret:
            optional: false
            secretName: {{ include "app.fullname" . }}-certificate
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30