{{- if has "observability" .Values.feature }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-app-monitor
  name: {{ include "app.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    scheme: http
  namespaceSelector:
    matchNames:
      - octo-happiness
  selector:
    matchLabels:
      app-with-metrics: 'quarkus-app'
{{- end }}