apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: "{{ .Release.Name }}-tls"
    cert-utils-operator.redhat-cop.io/cert-soon-to-expire-threshold: "1h"
    cert-utils-operator.redhat-cop.io/inject-CA: "true"
    cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
  name: {{ .Release.Name }}-route-grpc
spec:
  tls:
    termination: reencrypt
  port:
    targetPort: grpc
  to:
    kind: Service
    name: {{ .Release.Name }}-service