{{- if not (has "servicemesh" .Values.feature) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ .Release.Name }}-route-grpc
spec:
  port:
    targetPort: grpc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: {{ .Release.Name }}-service
{{- end }}