apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ .Release.Name }}-route-grpc-insecure
spec:
  tls:
    termination: edge
  port:
    targetPort: grpc
  to:
    kind: Service
    name: {{ .Release.Name }}-service