{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - '*'
  http:
    - match:
        - port: 9000
      route:
        - destination:
            host: {{ .Release.Name }}-service
            subset: v1
            port:
              number: 9000
    - match:
        - port: 8080
      route:
        - destination:
            host: {{ .Release.Name }}-service
            subset: v1
            port:
              number: 8080
{{- end }}