apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: main
    port: 8080
  - name: grpc
    port: 9000
  selector:
    {{- include "app.matchLabels" . | indent 4 }}