{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}-vs
spec:
  gateways:
    - octo-gateway
  hosts:
    - "octo-service-mesh.apps.ocp.ocp-gm.de"
  http:
    - name: "hello route"
      route:
        - destination:
            host: {{ .Release.Name }}-service
            subset: dev
            port:
              number: 8080
#      fault:
#        abort:
#          percentage:
#            value: 100
#          httpStatus: 415
{{- end }}