{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: octo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - hosts:
        - "octo-service-mesh.apps.ocp.ocp-gm.de"
      port:
        name: main
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ include "app.fullname" . }}-certificate
    - hosts:
        - "octo-service-mesh.apps.ocp.ocp-gm.de"
      port:
        number: 9000
        name: grpc
        protocol: GRPC
  {{- end }}