apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: http-main
    port: 8080
    targetPort: http-main
  - name: https-main
    port: 8443
    targetPort: http-main
  - name: grpc
    port: 9000
    targetPort: grpc
  selector:
    {{- include "app.matchLabels" . | indent 4 }}