{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: octo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - hosts:
        - "*"
      port:
        number: 443
        name: main
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ include "app.fullname" . }}-certificate
    - port:
        number: 80
        name: grpc
        protocol: grpc
      hosts:
        - "*"
      # tls:
      #   mode: SIMPLE
      #   credentialName: ingressgateway-certs
{{- end }}