apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: main
    port: 80
    targetPort: main
  - name: https
    port: 443
    targetPort: main
  - name: grpc
    port: 9000
    targetPort: grpc
  selector:
    {{- include "app.matchLabels" . | indent 4 }}