{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grpc
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 8080
        name: main
        protocol: HTTPS
      hosts:
        - "octo-service-mesh.apps.ocp.ocp-gm.de"
      tls:
        mode: SIMPLE
        credentialName: {{ .Release.Name }}-tls
    - port:
        number: 9000
        name: grpc
        protocol: GRPC
      hosts:
        - "octo-service-mesh-grpc.apps.ocp.ocp-gm.de"
{{- end }}