{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-dr
spec:
  host: {{ .Release.Name }}-service
  subsets:
    - name: v1
      labels:
        version: v1
{{- end }}