{{- if has "servicemesh" .Values.feature }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway-grpc
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: grpc
        number: 9000
        protocol: GRPC
    - hosts:
        - '*'
      port:
        name: main
        number: 80
        protocol: HTTP
{{- end }}