{{- if has "servicemesh" .Values.feature }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" . }}-certificate-grpc
  namespace: service-mesh
spec:
  secretName: ingressgateway-certs
  commonName: octo-service-mesh-gprc.apps.ocp.ocp-gm.de
  dnsNames:
    - 'octo-service-mesh-gprc.apps.ocp.ocp-gm.de'
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
{{- end }}